<h3>Find courses</h3>
<form action="/courses" method="get">
    <input type="search" name="term" value="<?= htmlspecialchars($term) ?>" />
    <input type="submit" value="Search" />
</form>
<table>
    <th>Название</th><th>Платный?</th>
    <?php foreach ($courses as $course): ?>
        <tr>

            <td>
                <?= htmlspecialchars($course['title']) ?>
            </td>
            <td>
                <?= htmlspecialchars($course['paid']) ?>
            </td>
        </tr>
    <?php endforeach ?>
</table>
<a href="/courses/new">Добавить новый</a>
<!-- END -->