<form action="/courses" method="post">
    <div>
        <label>
            Имя
            <input type="text" name="course[title]" value="<?= htmlspecialchars($course['title']) ?>">
        </label>
        <?php if (isset($errors['title'])): ?>
            <div><?= $errors['title'] ?></div>
        <?php endif ?>
    </div>
    <div>
        <label>
            Платный
            <input type="radio" name="course[paid]" value="Yes" checked> Да
            <input type="radio" name="course[paid]" value="No"> Нет
        </label>
    </div>

    <input type="submit" value="Add course">
</form>