<h3>My besties</h3>
<form method="get" action="/users">
    <input type="search" name="term" value="<?= htmlspecialchars($term) ?>" />
    <input type="submit" value="Search" />
<ul>
    <?php foreach ($users as $user) : ?>
        <li><a href="/users/<?=$user['id'] ?>"><?=htmlspecialchars($user['name']) ?> (<?= htmlspecialchars($user['email']) ?>)</a></li>
    <?php endforeach; ?>
</ul>
</form>
<a href="/users/new">Добавить нового</a>